language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
cache:
    directories:
        - $HOME/.cache/pip
install:
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt --only-binary=numpy
    - pip install -r .requirements-test.txt --only-binary=scipy
script:
    - py.test test/
